name: brevity
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  table_calendar: ^3.1.2
  supabase_flutter: ^2.5.7
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  time_picker_spinner: ^1.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/
    - .env
  uses-material-design: true

